# Generated by Django 5.0.9 on 2024-10-04 20:32

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag_post_author_post_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
